version: '3.3'

# Сервисы описывают контейнеры, которые будут запускаться
services:
  # api - это имя контейнера для GO API
  api:
    # build ищет Dockerfile в корне проекта и собирать его
    build: "."
    # Ставит 5000 порт из контейнера и привязывает его к случайному порту
    ports:
      - "5000"
    # Если контейнер упадет, он перезапустатся
    restart: "always"
    # Подключает API к общему api.network мосту
    networks:
      - "api.network"
    # Запускает 5 копий того же image
    deploy:
      replicas: 5
  # nginx контейнер
  nginx:
    image: nginx:latest
    # Соединяет conf файл контейнера с conf файлом в директории
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # Запуск nginx только после запуска всех контейнеров API
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - "api.network"
networks:
  api.network: